micronaut:
  application:
    name: petsdb

dbhost: 127.0.0.1
dbuser: root
dbpassword:
sauronuri: https://elasticsearch.dev.sefinland.sauron.eu-frankfurt-1.oracledx.com
sauronuser: sefinland
sauronpassword: